config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'

  get 'sessions/home'

  get 'sessions/profile'

  get 'sessions/setting'

  resources :opinions

  resources :restaurants

  resources :cuisines

  resources :users

  get 'welcome/index'

  resources :restaurant

  root 'welcome#index'

  match "signup", :to => "users#new", via: [:get, :post]
  match "login", :to => "sessions#login", via: [:get, :post]
  match "login_attempt", :to => "sessions#login_attempt", via: [:get, :post]
  match "logout", :to => "sessions#logout", via: [:get, :post]
  match "home", :to => "sessions#home", via: [:get, :post]
  match "profile", :to => "sessions#profile", via: [:get, :post]
  match "setting", :to => "sessions#setting", via: [:get, :post]

end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  belongs_to :user, :class_name => 'User', :foreign_key => 'id'
  belongs_to :restaurant, :class_name => 'Restaurant', :foreign_key => 'id'

  accepts_nested_attributes_for :user
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :set_opinion, only: [:show, :edit, :update, :destroy]

  # GET /opinions
  # GET /opinions.json
  def index
    @opinions = Opinion.all
  end

  # GET /opinions/1
  # GET /opinions/1.json
  def show
  end

  # GET /opinions/new
  def new
    @opinion = Opinion.new
  end

  # GET /opinions/1/edit
  def edit
  end

  # POST /opinions
  # POST /opinions.json
  def create
    @opinion = Opinion.new(opinion_params)

    respond_to do |format|
      if @opinion.save
        format.html { redirect_to @opinion, notice: 'Opinion was successfully created.' }
        format.json { render :show, status: :created, location: @opinion }
      else
        format.html { render :new }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opinions/1
  # PATCH/PUT /opinions/1.json
  def update
    respond_to do |format|
      if @opinion.update(opinion_params)
        format.html { redirect_to @opinion, notice: 'Opinion was successfully updated.' }
        format.json { render :show, status: :ok, location: @opinion }
      else
        format.html { render :edit }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opinions/1
  # DELETE /opinions/1.json
  def destroy
    @opinion.destroy
    respond_to do |format|
      format.html { redirect_to opinions_url, notice: 'Opinion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opinion
      @opinion = Opinion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opinion_params
      params.require(:opinion).permit(:rating)
    end
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/opinions/_form.html.erb
<%= form_for(@opinion) do |f| %>
  <% if @opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
      <% @opinion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/opinions/edit.html.erb
<h1>Editing Opinion</h1>

<%= render 'form' %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

app/views/opinions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Opinions</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @opinions.each do |opinion| %>
      <tr>
        <td><%= opinion.rating %></td>
        <td><%= link_to 'Show', opinion %></td>
        <td><%= link_to 'Edit', edit_opinion_path(opinion) %></td>
        <td><%= link_to 'Destroy', opinion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Opinion', new_opinion_path %>

app/views/opinions/new.html.erb
<h1>New Opinion</h1>

<%= render 'form' %>

<%= link_to 'Back', opinions_path %>

app/views/opinions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @opinion.rating %>
</p>

<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>